### PR TITLE
 Provide ccache 3.3.6 to help speed up code (re-)builds

### PR DESCRIPTION
**Pull request by jimklimov**

### CODE REVIEW

**Comment by oetiker** [comment]
what performance impact are you seeing from this ?

**Comment by jimklimov** [comment]
Depends on the project, usually the overall boost is around 3x to 10x for rebuilds of same or little-modified codebase (where many of the files and `-D` macros remain the same - the trick of `ccache` is that if cpp produced a source file content that was already built, and the compiler is the same, the cached binary object is a suitable quick answer); better so for C++ projects that take longer to compile in general. Big overheads that remain are the configure scripts and documentation generation, for example. And the preprocessor, per the more reliably looking legacy mode (a new mode is AFAIK to compare your source and system headers for not-modification since a cached build, facilitating a faster decision).

In case of illumos-gate, walking the Makefiles still takes a couple of hours - but doing less compilation had its impact of saving some half an hour consistently (I measured a year or so ago, so maybe now the balance of numbers is different).

**Comment by citrus-it** [comment]
Hi Jim,

Sorry for the delay - I've been catching up from the weekend.

This looks really useful and I plan to add support for it in our build scripts when I've done some more testing. Since it's an optional development tool I'm going to place it in our omnios-extra repository so have created a new PR over there based on yours but adjusted for the different file-system layout that's used for extra packages.

**Comment by jimklimov** [comment]
Ok, thanks. Generally it belongs wherever you provide the build essentials
like gcc (and perhaps should be distributed as part of such an essential
metapackage) :)

2018-02-06 16:57 GMT+01:00 Andy Fiddaman <notifications@github.com>:

**Pull request closed without merging**
